# 추측 통계의 기본

- 추측통계 : 일부 데이터로 전체의 통계적 성질을 추측하는 것

![](추측통계예시.png)

## 모집단과 표본


- 모집단(population) 
    - 조사 대상이 되는 관측 가능한 개체로 된 집단 전체(관심있는 집단)
    
    
- 표본(sample)
    - 모집단에서 선택된 모집단 구성단위의 일부


<img src='모집단과표본.jpg' width=500 height=500>

### 표본 추출 방법
- 무작위 추출(임의 추출) : 임의로 표본을 추출하는 방법
- 복원 추출 : 여러차례 동일한 표본이 선택될수 있는 방법
- 비복원 추출: 동일한 표본은 한번만 선택되는 방법

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline


In [4]:
df = pd.read_csv('../data/data/ch4_scores400.csv')
scores = np.array(df['score'])
scores[:10]


array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80], dtype=int64)

In [19]:
#복원 추출
np.random.seed(0)
np.random.choice([1,2,3],3)

array([1, 2, 1])

In [20]:
#비복원추출
np.random.seed(0)
np.random.choice([1,2,3],3,replace=False)

array([3, 2, 1])

In [21]:
np.random.seed(0)
sample = np.random.choice(scores, 20)

# 표본 평균
sample.mean()


70.4

#전체 데이터의 평균
scores.mean()


In [24]:
for i in range(5):
    sample = np.random.choice(scores, 20)
    print(f'{i+1}번째 무작위 추출로 얻은 표본평균', sample.mean())

#표본 평균은 70점 전후 이지만 나름대로 산포도도 나타내고 있음

1번째 무작위 추출로 얻은 표본평균 70.7
2번째 무작위 추출로 얻은 표본평균 71.9
3번째 무작위 추출로 얻은 표본평균 71.25
4번째 무작위 추출로 얻은 표본평균 67.4
5번째 무작위 추출로 얻은 표본평균 67.7
