### 인덱싱과 슬라이싱 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

 #### 인덱싱
  - 파이썬 리스트와 동일한 개념으로 사용
  - ,를 사용하여 각 차원의 인덱스에 접근 가능

- 1차원 벡터 인덱싱

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[3]=100
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

- 2차원 행렬 인덱싱

In [8]:
x=np.arange(10).reshape(2,5)
x


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
x[0,2] #[0]번째 배열의 [2]번째자리 값에 접근

2

In [7]:
x[0]

array([0, 1, 2, 3, 4])

 #### 슬라이싱
  - 리스트, 문자열 slicing과 동일한 개념으로 사용
  - ,를 사용하여 각 차원 별로 슬라이싱 가능
  

- 1차원 벡터 슬라이싱

In [10]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x=np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
x[0, :2]
x[:1,:2] # [0] 번째 배열의 [2] 번째 인덱스값을 배열로 반환
x[:1,2]  

array([0, 1])

array([[0, 1]])

array([2])

 ## ndarray shape 변경하기
 #### ravel, np.ravel
   - 다차원배열을 1차원으로 변경
   - 'order' 파라미터
     - 'C' - row 우선 변경
     - 'F - column 우선 변경
   - 원본을 참조 함

In [21]:
x = np.arange(15).reshape(3, 5)
print(x)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
np.ravel(x,order='F') # 열을 우선으로, 앞쪽 인덱스를 채워가며 1차원 배열로 변환
np.ravel(x,order='c') # 행을 우선으로 - 기본설정 값


array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
# 원본을 참조 함
temp = x.ravel()
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
temp[0]=100
temp
x  # 원본에도 변화가 생긴다!

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

 #### flatten
  - 다차원 배열을 1차원으로 변경
  - ravel과의 차이점: copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
  - 'order' 파라미터
    - 'C' - row 우선 변경
    - 'F - column 우선 변경


In [25]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [26]:
t2 = y.flatten(order='F')
t2

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [27]:
t2[0]=100
t2
y #원본에 영향 끼치지 않았음


array([100,   5,  10,   1,   6,  11,   2,   7,  12,   3,   8,  13,   4,
         9,  14])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### reshape 함수
  - array의 shape을 다른 차원으로 변경
  - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
  - 사용 예) 이미지 데이터 벡터화 
      - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨


In [28]:
x = np.arange(36)
print(x)
print(x.shape)
print(x.ndim) # 차원 수 출력


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [29]:
y= x.reshape(6,6)
y
y.shape
y.ndim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

(6, 6)

2

In [30]:
a=np.arange(1,9)
a
b=a.reshape(2,2,2)
b
b.shape
b.ndim #차원수 출력


array([1, 2, 3, 4, 5, 6, 7, 8])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

(2, 2, 2)

3

In [31]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [32]:
k=x.reshape(3,3,-1) # 행을 결정하고 열을 -1 로 주면 원소의 개수에 따라 열 개수가 정해짐
k
k.shape
k.ndim


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

(3, 3, 4)

3

In [33]:
k=x.reshape(3,-1,3) # 행을 결정하고 열을 -1 로 주면 원소의 개수에 따라 열 개수가 정해짐
k
k.shape
k.ndim


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

(3, 4, 3)

3

In [34]:
x_1 = np.arange(35)
x_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

- 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능

In [35]:
x_1.reshape(3,3,4) #cannot reshape array of size 35 into shape (3,3,4)

ValueError: cannot reshape array of size 35 into shape (3,3,4)

In [36]:
x_1.reshape(3,2,2) #cannot reshape array of size 35 into shape (3,2,2)


ValueError: cannot reshape array of size 35 into shape (3,2,2)