### numpy에서 자주 사용되는 함수들 정리



In [1]:
import numpy as np
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

#### numpy documentation
  - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
  - numpy에서 제공되는 함수등에 대한 문서


In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.9409545  0.2388438  0.11049246 0.30226054 0.24639654]
 [0.53998199 0.81399131 0.5529769  0.65001811 0.63670484]
 [0.23639609 0.86894706 0.04280139 0.48584294 0.5621091 ]]


 #### 연산 함수
  - add, subtract, multiply, divide


In [3]:
np.add(x,y)
np.divide(x,y)
np.multiply(x,y)
np.subtract(x,y)

array([[ 0.9409545 ,  1.2388438 ,  2.11049246,  3.30226054,  4.24639654],
       [ 5.53998199,  6.81399131,  7.5529769 ,  8.65001811,  9.63670484],
       [10.23639609, 11.86894706, 12.04280139, 13.48584294, 14.5621091 ]])

array([[  0.        ,   4.18683675,  18.10078282,   9.92521233,
         16.23399444],
       [  9.25956811,   7.37108602,  12.65875666,  12.3073495 ,
         14.13527811],
       [ 42.30188372,  12.65899902, 280.36470916,  26.75761842,
         24.90619696]])

array([[0.        , 0.2388438 , 0.22098492, 0.90678161, 0.98558615],
       [2.69990994, 4.88394789, 3.87083829, 5.20014484, 5.73034357],
       [2.36396092, 9.55841768, 0.51361671, 6.31595822, 7.86952743]])

array([[-0.9409545 ,  0.7611562 ,  1.88950754,  2.69773946,  3.75360346],
       [ 4.46001801,  5.18600869,  6.4470231 ,  7.34998189,  8.36329516],
       [ 9.76360391, 10.13105294, 11.95719861, 12.51415706, 13.4378909 ]])

In [4]:
x+y

array([[ 0.9409545 ,  1.2388438 ,  2.11049246,  3.30226054,  4.24639654],
       [ 5.53998199,  6.81399131,  7.5529769 ,  8.65001811,  9.63670484],
       [10.23639609, 11.86894706, 12.04280139, 13.48584294, 14.5621091 ]])

In [5]:
x-y

array([[-0.9409545 ,  0.7611562 ,  1.88950754,  2.69773946,  3.75360346],
       [ 4.46001801,  5.18600869,  6.4470231 ,  7.34998189,  8.36329516],
       [ 9.76360391, 10.13105294, 11.95719861, 12.51415706, 13.4378909 ]])